name: hop_git
version: 0.1.0+1
author: Kevin Moore <kevmoo@google.com>
description: Hop tasks for interacting with Git
homepage: https://github.com/kevmoo/hop_git
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  git: '>=0.4.1 <0.5.0'
  hop: '>=0.30.0 <0.32.0'
dev_dependencies:
  bot_io: '>=0.26.3 <0.27.0'
  hop_docgen: '>=0.1.3 <0.2.0'
  hop_unittest: '>=0.1.0 <0.2.0'
  unittest: '>=0.11.0 <0.12.0'
